spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: akash
    password: akash
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:
          orderConfirmation: com.akash.ecommerce.kafka.OrderConfirmation


application:
  config:
    customer-url: http://localhost:8090/api/v1/customers   #for testing , we will use from api gateway later on
    product-url: http://localhost:8060/api/v1/product    #for testing , we will use from api gateway later on
    payment-url: http://localhost:8050/api/v1/payments    #for testing , we will use from api gateway later on



server:
  port: 8070
